"""empty message

Revision ID: b6f1bcaffe9e
Revises: f3ec96a9351b
Create Date: 2025-11-27 20:59:00.850653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f1bcaffe9e'
down_revision: Union[str, Sequence[str], None] = 'f3ec96a9351b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_jti', sa.String(), nullable=True))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'refresh_jti')
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###
